### ISSUE TITLE
Cut n paste onto a long line upsets the line numbers

### ISSUE THREAD

**Issue by domesticmouse** [csells/flutter_texteditor_linenums#1]
<img width="912" alt="Screen Shot 2021-09-20 at 2 57 11 pm" src="https://user-images.githubusercontent.com/30503/133958556-d8c243c5-1e60-40df-95f2-5fd0b000e7db.png">

**Comment by csells** [comment]
should be fixed with https://github.com/csells/flutter_texteditor_linenums/pull/2

**Comment by domesticmouse** [comment]
Confirmed fixed.
